### ISSUE TITLE
Mes modifications

### ISSUE THREAD

**Issue by Minizquest** [HuLijin/Lyrium#6]
Dresser ici la liste des trucs a modifier, puis penser a cocher quand c'est fait.

=> les tables des effets entropiques dans la liste des règles alternatives est a compléter

**Comment by Minizquest** [comment]
=> j'ai modifié les avantages, j'ai rajouté chanceux
=> j'ai complété les tours de passe passe et modifié la règle pour les acquérir
=> j'ai modifié le déroulement du combat, surtout la partie sur les actions complexes

**Comment by Minizquest** [comment]
Est ce que le sacrifice de dé ne devrais pas atribuer un bonus au dégâts ? 
Il se trouve que sacrifier ses dés n'octroie qu'un léger bonus, en doublant les dégâts peut etre que les joueurs choisiront plutôt cette option ?

En sachant que un coup sacrifié a plus de chance d'etre un coup critique, utilisé au bon moment ça peut etre un finisher ?

**Comment by HuLijin** [comment]
Ce sont des questions pense-bête pour toi ou ce sont des questions pour moi ?
